# ---------------------Hamza Saleem---------------
library(gplots)
install.packages('gplots')
library(pheatmap)
library(tidyverse)
library(RColorBrewer)
library(cluster) #clustering algorithms
library(factoextra)
font_import()
install.packages('remotes')
library(ggplot2)
library(showtext)
library(extrafont)
install.packages('extrafont
                 ')
install.packages('showtext')
library(extrafont)
font_install('fontcm')
Sys.setenv(R_GSCMD="C:/Program Files/gs/gs9.05/bin/gswin32c.exe")
y

font_add(family = "ComicSansMS", regular = "Comic.ttf")

showtext_auto()
warnings()

windowsFonts(A = windowsFont("Calibri"))
pheatmap(data, family= "A")

font_add(family = "FiraCodeRegular", regular = "FIRACODE-REGULAR.ttf")
install.packages("extrafont")
library(extrafont)

font_add(family = "TimesNewRoman", regular = "times.ttf")

#  ----------------Dr.Naawaz --------
library(corrplot)
library(factoextra)
library(FactoMineR)
install.packages("RColorBrewer")
install.packages("heat_map_save")
install.packages("complexheatmap")
install.packages("Heat_map_save")
install.packages('reticulate')
reticulate::install_miniconda()
reticulate::conda_install('r-reticulate', 'python-kaleido')
reticulate::conda_install('r-reticulate', 'plotly', channel = 'plotly')
reticulate::use_miniconda('r-reticulate')
library(ComplexHeatmap)
library(RColorBrewer)
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("ComplexHeatmap")
install.packages("https://cran.r-project.org/src/contrib/Archive/GetoptLong/GetoptLong_0.1.8.tar.gz", repo = NULL)
BiocManager::install("ComplexHeatmap")
library(circlize)

# ----------------------Compplexheatmap---------------
lapply(.packages(all.available = TRUE), function(xx)library(xx,character.only = TRUE))
library(ggplot2)
library(corrplot)
library(ggplot2)
library(reshape2)
library("d3heatmap")
install.packages("d3heatmap")
install.packages('pheatmap')
# ----------------------TestR-------------
install.packages("ggpubr","kassambara")
library(ggpubr)
install.packages("extrafont")
my_packages<-as.data.frame(installed.packages()[,c(1,3:4)])
my_packages<-my_packages[is.na(my_packages$Priority),1:2, drop=FALSE]
rownames(my_packages)<-NULL
head(my_packages)
View(my_packages)
install.packages("ggcorrplot")
install.packages("chron")
install.packages("gridGraphics")
library(gridGraphics)
install.packages("lattice")
install.packages("plotrix")
install.packages("graphics")
install.packages("latticeExtra")
library(ggplot2)
install.packages("factoextra")
install.packages("FactoMineR")
install.packages("hrbrthemes")
library(hrbrthemes)
install.packages("plotly")
library(plotly)
install.packages("heatmaply")
library(heatmaply)
install.packages("pheaheatmap")

install.packages("pheatmap")
install.packages("reshape2")
library(heatmaply)
install.packages("heatmap.2")
webshot::install_phantomjs()
heatmaply(mtcars, file = "heatmaply_plot.pdf")
library(viridis)
library(chron)
library(lattice)
library(plotrix)
library(graphics)
#--------------------Saving a graph----------
bitmap("rehan.tiff", height = 4, width = 4, units = 'in', type="tifflzw", res=300)
dev.off()
par(mfrow = c(1,1))
jpeg("image.tiff",
     width = 6, height = 6, units = "in", res = 600)
dev.off()

p<- plot(iris)
ggsave("iris.png", height = 6, width = 6, dpi = 600)
p
dev.off()
# ---------------------Learning-----------
install.packages("rstudioapi")
install.packages("PerformanceAnalytics")
library(PerformanceAnalytics)
library(gclus)
install.packages("Hmisc")
install.packages("correlation_matrix")
install.packages("xlsx")
library(Hmisc)
library(xlsx)
